version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - ./:/app
    working_dir: /app
    user: '1000:1000'
    ports:
      - 8000:8000
    command: php -S 0.0.0.0:8000 -t /app

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    ports:
        - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: qwerty
    ports:
      - 9000:80